#!groovy
node {
    echo 'Hallo'
    checkout scm
    checkout([$class: 'GitSCM', 
    			branches: [[name: '*/master']], 
    			doGenerateSubmoduleConfigurations: false, 
    			extensions: [], 
    			submoduleCfg: [], 
    			userRemoteConfigs: [[credentialsId: '16d61fc2-c8a0-4d2c-a9c6-d3c25273d193', 
    								url: 'https://github.com/MaheswariRajendran/test-maven']]])
    								
    stage('Build') {
    	
    	
    }
    
     stage('Test') {
     	bat '''cd test_jenkins_maven'''
      junit '**/target/surefire-reports/*.xml'
     
     }
     
     stage('deploy'){
     
     	bat '''cd test_jenkins_maven
mvn verify'''

     }
    
    
}